#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Taxi.Droid.Resource", IsApplication=true)]

namespace Taxi.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int googleMap = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int btnCancel = 2131034114;
			
			// aapt resource value: 0x7f050010
			public const int btnForgot = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int btnOk = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int btnSignIn = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int btnSignUp = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int btnSignUpFragment = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int checkBoxRemenber = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int requestTaxi = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int txtEmail = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int txtFirstName = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int txtLastName = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int txtOr = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int txtPassword = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int txtPasswordLogin = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int txtUserID = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int txtUserNameLogin = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int txtViewConfirmation = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Confirmation_Popup = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog_sign_up = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
